---
- name: Setup Kubernetes Networking
  hosts: k8s_master
  become: true
  tasks:
    - name: Install Flannel CNI plugin
      command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
      when: inventory_hostname == 'kubermaster-ub'

