apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-admin-binding
subjects:
  - kind: User
    name: kubernetes-admin  # This should match the username of the kubernetes-admin user
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: kubernetes-admin
  apiGroup: rbac.authorization.k8s.io
