apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # Make sure this matches your use case, you can name it "kubernetes-admin" or something else
  name: kubernetes-admin
rules:
  - apiGroups: [""]
    resources: ["users"]
    verbs: ["impersonate"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["rolebindings"]
    verbs: ["create", "get", "list", "update", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles"]
    verbs: ["create", "get", "list", "update", "delete"]
