---
- name: Create ClusterRoleBinding for kubernetes-admin
  hosts: k8s_master
  tasks:
    - name: Create clusterrolebinding for kubernetes-admin using k8s module
      k8s:
        kubeconfig: "~/kube/config"  # Adjust the path to your kubeconfig file if necessary
        state: present
        definition:
          kind: ClusterRoleBinding
          apiVersion: rbac.authorization.k8s.io/v1
          metadata:
            name: kubernetes-admin-binding
          roleRef:
            kind: ClusterRole
            name: cluster-admin
            apiGroup: rbac.authorization.k8s.io
          subjects:
            - kind: User
              name: kubernetes-admin
              apiGroup: rbac.authorization.k8s.io
