---
- name: Create Kubernetes ClusterRole and ClusterRoleBinding
  hosts: k8s_master
  gather_facts: no
  tasks:
    - name: Create ClusterRole for impersonation permissions
      #kubernetes.core.k8s:
      k8s
        kubeconfig: "~/.kube/config"  # Optional, specify your kubeconfig path if different
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRole
          metadata:
            name: kubernetes-admin
          rules:
            - apiGroups: [""]
              resources: ["users"]
              verbs: ["impersonate"]
            - apiGroups: ["rbac.authorization.k8s.io"]
              resources: ["rolebindings"]
              verbs: ["create", "get", "list", "update", "delete"]
            - apiGroups: ["rbac.authorization.k8s.io"]
              resources: ["roles"]
              verbs: ["create", "get", "list", "update", "delete"]
