- name: Create ClusterRoleBinding for kubernetes-admin
  hosts: k8s_master
  gather_facts: no
  tasks:
    - name: Bind kubernetes-admin to cluster-admin role
      k8s:
        api_version: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        name: kubernetes-admin-clusterrolebinding
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: kubernetes-admin-clusterrolebinding
          subjects:
            - kind: User
              name: kubernetes-admin  # The user you're granting permissions to
              apiGroup: rbac.authorization.k8s.io
          roleRef:
            kind: ClusterRole
            name: cluster-admin  # Grants full cluster-wide admin rights
            apiGroup: rbac.authorization.k8s.io
