---
- name: Stopping all kubelet services
  hosts: k8s_workers
  become: yes
  tasks:
    - name: Check listening ports for etcd and kube
      shell: "netstat -tulpn | grep -E 'etcd|kube' | awk -F/ '{ print $2 }' | uniq"
      register: result
      failed_when: result.rc != 0


    - name: Stop kube-services-items on worker nodes
      systemd:
        name: "{{ item }}"
        state: stopped
      with_items: result.stdout_lines






